//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductData.DBconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> rate { get; set; }
        public string Total { get; set; }
        public string picname { get; set; }
    }
}
